# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
my_rand_unif <- function() {
    .Call('_lvmcomp_my_rand_unif', PACKAGE = 'lvmcomp')
}

#' @export
obj_func_cpp <- function(sigma, sigma_hat) {
    .Call('_lvmcomp_obj_func_cpp', PACKAGE = 'lvmcomp', sigma, sigma_hat)
}

#' @export
calcu_sigma_cmle_cpp <- function(theta, tol) {
    .Call('_lvmcomp_calcu_sigma_cmle_cpp', PACKAGE = 'lvmcomp', theta, tol)
}

#' @export
log_sum_exp2 <- function(tmp) {
    .Call('_lvmcomp_log_sum_exp2', PACKAGE = 'lvmcomp', tmp)
}

#' @export
update_sigma_one_step2 <- function(theta0, B0, B_res1, B_res2, B_mis_info, mcn, alpha, step, c1, c2) {
    .Call('_lvmcomp_update_sigma_one_step2', PACKAGE = 'lvmcomp', theta0, B0, B_res1, B_res2, B_mis_info, mcn, alpha, step, c1, c2)
}

#' @export
calcu_sigma_cmle_cpp1 <- function(theta) {
    .Call('_lvmcomp_calcu_sigma_cmle_cpp1', PACKAGE = 'lvmcomp', theta)
}

#' @export
test_deriv <- function(B0, theta0) {
    .Call('_lvmcomp_test_deriv', PACKAGE = 'lvmcomp', B0, theta0)
}

#' @export
oakes <- function(theta0, response, Q, Sigma, A, d, M = 400L) {
    .Call('_lvmcomp_oakes', PACKAGE = 'lvmcomp', theta0, response, Q, Sigma, A, d, M)
}

#' @export
obj_det <- function(theta, B) {
    .Call('_lvmcomp_obj_det', PACKAGE = 'lvmcomp', theta, B)
}

#' @export
bfgs_update <- function(theta0, B0, flag, tol = 1e-4) {
    .Call('_lvmcomp_bfgs_update', PACKAGE = 'lvmcomp', theta0, B0, flag, tol)
}

neg_loglik_logi_partial_credit <- function(theta, response_j, A_j, D_j) {
    .Call('_lvmcomp_neg_loglik_logi_partial_credit', PACKAGE = 'lvmcomp', theta, response_j, A_j, D_j)
}

neg_loglik_deri_partial_credit <- function(theta, response_j, A_j, D_j) {
    .Call('_lvmcomp_neg_loglik_deri_partial_credit', PACKAGE = 'lvmcomp', theta, response_j, A_j, D_j)
}

my_Logistic_cpp <- function(XX, YY, beta0, d0) {
    .Call('_lvmcomp_my_Logistic_cpp', PACKAGE = 'lvmcomp', XX, YY, beta0, d0)
}

my_Logistic_cpp_partial <- function(XX, YY, beta0, D0) {
    .Call('_lvmcomp_my_Logistic_cpp_partial', PACKAGE = 'lvmcomp', XX, YY, beta0, D0)
}

#' @export
stem_mirtc <- function(response, Q, A0, d0, theta0, sigma0, T, parallel) {
    .Call('_lvmcomp_stem_mirtc', PACKAGE = 'lvmcomp', response, Q, A0, d0, theta0, sigma0, T, parallel)
}

stem_pcirtc <- function(response, Q, A0, D0, theta0, sigma0, T, parallel) {
    .Call('_lvmcomp_stem_pcirtc', PACKAGE = 'lvmcomp', response, Q, A0, D0, theta0, sigma0, T, parallel)
}

#' @export
stem_simu <- function(response, Q, A0, d0, B0, theta0, ave_from = 100L, max_steps = 200L, print_proc = TRUE) {
    .Call('_lvmcomp_stem_simu', PACKAGE = 'lvmcomp', response, Q, A0, d0, B0, theta0, ave_from, max_steps, print_proc)
}

#' @export
sa_penmirt <- function(response, theta, A, d, B, lambda, zero, anchor, alpha, step = 1, max_steps = 200L) {
    .Call('_lvmcomp_sa_penmirt', PACKAGE = 'lvmcomp', response, theta, A, d, B, lambda, zero, anchor, alpha, step, max_steps)
}

#' @export
sa_penmirt1 <- function(response, theta, A, d, B, lambda, zero, anchor, alpha, step = 1, ave_from = 50L, max_steps = 200L, tol = 0.01) {
    .Call('_lvmcomp_sa_penmirt1', PACKAGE = 'lvmcomp', response, theta, A, d, B, lambda, zero, anchor, alpha, step, ave_from, max_steps, tol)
}

#' @export
sa_mirt_conf <- function(response, A, Q, d, B, theta, alpha, step = 1.0, ave_from = 100L, max_steps = 200L) {
    .Call('_lvmcomp_sa_mirt_conf', PACKAGE = 'lvmcomp', response, A, Q, d, B, theta, alpha, step, ave_from, max_steps)
}

#' @export
sa_mirt_conf_no_ave <- function(response, A, Q, d, B, theta, alpha, step = 1.0, max_steps = 200L) {
    .Call('_lvmcomp_sa_mirt_conf_no_ave', PACKAGE = 'lvmcomp', response, A, Q, d, B, theta, alpha, step, max_steps)
}

#' @export
MHRM_conf <- function(response, A, Q, d, B, theta, step = 1.0, max_steps = 200L) {
    .Call('_lvmcomp_MHRM_conf', PACKAGE = 'lvmcomp', response, A, Q, d, B, theta, step, max_steps)
}

#' @export
sa_mirt_conf1 <- function(response, A, Q, d, B, theta, alpha, step = 1.0, ave_from = 100L, max_steps = 200L) {
    .Call('_lvmcomp_sa_mirt_conf1', PACKAGE = 'lvmcomp', response, A, Q, d, B, theta, alpha, step, ave_from, max_steps)
}

#' @export
sa_mirt_arma <- function(response, Q, A0, d0, theta0, A_true, d_true, alpha, C0, window_size = 100L, block_size = 20L, max_steps = 2000L, print_proc = FALSE) {
    .Call('_lvmcomp_sa_mirt_arma', PACKAGE = 'lvmcomp', response, Q, A0, d0, theta0, A_true, d_true, alpha, C0, window_size, block_size, max_steps, print_proc)
}

#' @export
stem_init <- function(response, Q, A0, d0, theta0, max_steps, window_size = 40L, block_size = 20L, tol = 0.05) {
    .Call('_lvmcomp_stem_init', PACKAGE = 'lvmcomp', response, Q, A0, d0, theta0, max_steps, window_size, block_size, tol)
}

#' @export
test_r <- function(rows, cols) {
    .Call('_lvmcomp_test_r', PACKAGE = 'lvmcomp', rows, cols)
}

#' @export
test_r1 <- function(rows, cols) {
    .Call('_lvmcomp_test_r1', PACKAGE = 'lvmcomp', rows, cols)
}

