# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
calcu_sigma_cmle_cpp <- function(theta, tol) {
    .Call('_lvmcomp_calcu_sigma_cmle_cpp', PACKAGE = 'lvmcomp', theta, tol)
}

neg_loglik_logi_partial_credit <- function(theta, response_j, A_j, D_j) {
    .Call('_lvmcomp_neg_loglik_logi_partial_credit', PACKAGE = 'lvmcomp', theta, response_j, A_j, D_j)
}

neg_loglik_deri_partial_credit <- function(theta, response_j, A_j, D_j) {
    .Call('_lvmcomp_neg_loglik_deri_partial_credit', PACKAGE = 'lvmcomp', theta, response_j, A_j, D_j)
}

my_Logistic_cpp <- function(XX, YY, beta0, d0) {
    .Call('_lvmcomp_my_Logistic_cpp', PACKAGE = 'lvmcomp', XX, YY, beta0, d0)
}

my_Logistic_cpp_partial <- function(XX, YY, beta0, D0) {
    .Call('_lvmcomp_my_Logistic_cpp_partial', PACKAGE = 'lvmcomp', XX, YY, beta0, D0)
}

stem_mirtc <- function(response, Q, A0, d0, theta0, sigma0, T, parallel) {
    .Call('_lvmcomp_stem_mirtc', PACKAGE = 'lvmcomp', response, Q, A0, d0, theta0, sigma0, T, parallel)
}

stem_pcirtc <- function(response, Q, A0, D0, theta0, sigma0, T, parallel) {
    .Call('_lvmcomp_stem_pcirtc', PACKAGE = 'lvmcomp', response, Q, A0, D0, theta0, sigma0, T, parallel)
}

